#!/bin/bash

RETRY_NUM=30
RETRY_EVERY=10

NUM=$RETRY_NUM
until ssh -i %private_key_filename% root@%instance_ip%
do
  1>&2 echo "Failed to connect, retrying $NUM more times, next in $RETRY_EVERY seconds"
  sleep $RETRY_EVERY
  ((NUM--))

  if [ $NUM -eq 0 ]
  then
    1>&2 echo "Connection unsuccessful after $RETRY_NUM tries"
    exit 1
  fi
done
