#!/bin/bash

STACK=$(pulumi stack --show-name)
DROPLET_IP=$(pulumi stack output droplet_public_ip)
PRIVATE_KEY_FILE="id_cobra_rsa_$STACK"
pulumi stack output private_key_openssh --show-secrets > "$PRIVATE_KEY_FILE"

echo "Retrieved connection details, connecting..."
ssh -i "$PRIVATE_KEY_FILE" "root@$DROPLET_IP" "$@"
