CREATE USER vscode CREATEDB;
CREATE DATABASE vscode WITH OWNER vscode;
CREATE USER cobra WITH PASSWORD 'cobra' CREATEDB;
CREATE DATABASE cobra_development WITH OWNER cobra;
CREATE DATABASE cobra_test WITH OWNER cobra;
